id: opecha:P000331
initial_creation_type: ocr
source_metadata:
  id: bdr:W22068
  title: མངའ་རིས་གསེར་རྫོང་།
  volume:
    446e2a72738945a1a268da65bc9cc636:
      image_group_id: I1KG17259
      title: Volume 1 of mnga' ris gser rdzong
      volume_number: 1
      total_pages: 252
  author: ''
ebook_metadata:
  title: མངའ་རིས་གསེར་རྫོང་།
  author: ''
  sku: P000331
  cover: cover.jpg
  layers:
  - pagination
