id: P000331
initial_creation_type: ocr
created_at: 12/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W22068
  title: མངའ་རིས་གསེར་རྫོང་།
  author: ''
  volumes:
    446e2a72738945a1a268da65bc9cc636:
      image_group_id: I1KG17259
      title: Volume 1 of mnga' ris gser rdzong
      volume_number: 1
      total_pages: 252
      base_file: v001.txt
